#!/usr/bin/env node
/**
 * Compile standalone AJV validators from /schemas into /scripts/validators.
 * Run ONLY on an internet-connected box that has ajv + ajv-formats installed.
 * Output files are self-contained CJS modules (no runtime deps).
 */
const fs = require('fs');
const path = require('path');
const Ajv = require('ajv');
const addFormats = require('ajv-formats');
const standaloneCode = require('ajv/dist/standalone').default;

const ROOT = path.resolve(__dirname, '..');
const SCHEMAS = [
  { in: 'META.schema.json', out: 'meta.cjs' },
  { in: 'sections.schema.json', out: 'sections.cjs' },
  { in: 'rules.schema.json', out: 'rules.cjs' },
];

function compileOne(schemaFile, outFile) {
  const ajv = new Ajv({ strict: true, code: { source: true } });
  addFormats(ajv);
  const schema = JSON.parse(fs.readFileSync(path.join(ROOT, 'schemas', schemaFile), 'utf8'));
  const validate = ajv.compile(schema);
  const code = standaloneCode(ajv, validate);
  const banner = `/* Standalone validator generated by ajv@${require('ajv/package.json').version}
     Schema: ${schemaFile}
     DO NOT EDIT MANUALLY. Regenerate with: node scripts/compile-audit.js */\n`;
  fs.writeFileSync(path.join(ROOT, 'scripts', 'validators', outFile), banner + code);
  console.log(`wrote scripts/validators/${outFile}`);
}

SCHEMAS.forEach(s => compileOne(s.in, s.out));
