name: Manual Ingest
on:
  workflow_dispatch:
    inputs:
      batch:
        description: 'Path to .links.txt file'
        required: true
jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Run Ingestion
        run: |
          chmod +x scripts/ingest-full.sh
          ./scripts/ingest-full.sh --batch ${{ github.event.inputs.batch }} --offline
