name: Registry Guard
on:
  push:
    paths:
      - 'methodologies/**'
      - 'registry.json'
      - '.github/workflows/registry-guard.yml'
  pull_request:
    paths:
      - 'methodologies/**'
      - 'registry.json'
      - '.github/workflows/registry-guard.yml'
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Skip if only staging/** changed
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            DIFF=$(git diff --name-only HEAD^)
          else
            DIFF=$(git ls-files)
          fi
          echo "$DIFF" | grep -v '^staging/' | grep -q . && echo "Proceeding" || { echo "Only staging changed; exiting."; exit 0; }
      - name: Ensure registry mirrors /methodologies
        run: |
          ls methodologies | jq -R -s 'split("\n")|map(select(length>0))|map("methodologies/"+.)' > /tmp/dirs.json
          jq -S . registry.json > /tmp/registry.json
          diff -u /tmp/dirs.json <(jq -r '.[].path' /tmp/registry.json | jq -R -s 'split("\n")|map(select(length>0))' | jq -c) || true
          # simple presence check:
          missing=$(comm -23 <(jq -r '.[]' /tmp/dirs.json | sort) <(jq -r '.[]?.path' registry.json | sort) || true)
          if [ -n "$missing" ]; then echo "Missing in registry: $missing"; exit 1; fi

