name: registry-guard
on:
  push:
    branches-ignore: ['bot/**']
    paths:
      - 'methodologies/**'
      - 'schemas/**'
      - 'tools/**'
  pull_request:
    branches:
      - 'main'
      - 'feat/**'
    paths:
      - 'methodologies/**'
      - 'schemas/**'
      - 'tools/**'
jobs:
  guard:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !startsWith(github.ref_name, 'bot/') &&
      !(github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'bot/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20.11.1'
      - name: verify registry entries
        run: |
          node -e "const fs=require('fs');const reg=JSON.parse(fs.readFileSync('registry.json'));if(!Array.isArray(reg)){process.exit(1)};process.exit(reg.every(e=>e&&e.path&&fs.existsSync(e.path))?0:1)"
