name: Registry Guard
on: [push, pull_request]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure registry mirrors /methodologies
        run: |
          # discover method directories by the presence of META.json (recursive)
          find methodologies -type f -name META.json -print0 | xargs -0 -n1 dirname | sort -u \
            | jq -R -s 'split("\n")|map(select(length>0))' > /tmp/dirs.json
          jq -S . registry.json > /tmp/registry.json
          # Accept both legacy ".path" or modern ".paths.meta" (dirname)
          jq -r '
            .methodologies
            | map(
                ( .path // ( .paths.meta // "" ) ) as $p
                | if ($p|length)>0 then ($p|sub("/META.json$";"")) else "" end
              )
            | map(select(length>0))
            | .[]
          ' registry.json > /tmp/registry_paths.txt
          diff -u /tmp/dirs.json <(jq -R -s 'split("\n")|map(select(length>0))' /tmp/registry_paths.txt | jq -c) || true
          # simple presence check:
          missing=$(comm -23 <(jq -r '.[]' /tmp/dirs.json | sort) <(sort /tmp/registry_paths.txt) || true)
          if [ -n "$missing" ]; then echo "Missing in registry: $missing"; exit 1; fi
