name: registry-guard
on:
  push:
  pull_request:
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: verify registry entries
        run: |
          node -e "const fs=require('fs');const reg=JSON.parse(fs.readFileSync('registry.json'));function check(entries){return entries.every(e=>fs.existsSync(e.path));}if(!check([...(reg.standard||[]),...(reg.stage||[])])){process.exit(1);}"
