name: schema-validate
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      NODE_PATH: scripts/.node/node_modules
      NPM_CONFIG_FUND: "false"
      NPM_CONFIG_AUDIT: "false"
      NPM_CONFIG_OFFLINE: "true"
      NPM_CONFIG_REGISTRY: "http://127.0.0.1:4873"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Prepare vendored AJV locally
        run: |
          mkdir -p scripts/.node
          cd scripts/.node
          npm init -y >/dev/null 2>&1
          npm i --no-fund --no-audit --prefer-offline --no-save \
            ../../vendor/npm/ajv-8.17.1.tgz \
            ../../vendor/npm/ajv-formats-2.1.1.tgz
      - name: Build standalone validators
        run: npm run build:validators
      - name: Print fingerprints
        run: npm run prevalidate:offline
      - name: Validate (offline)
        run: npm run validate:offline
