name: schema-validate
on:
  push:
  pull_request:
jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Offline schema validation
        run: node scripts/validate-offline.js
      - name: Meta-driven source hash check
        run: bash scripts/check-source-hash.sh
