name: schema-validate
on:
  push:
  pull_request:
jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      # jq not required; use Node-based checks only
      - name: Derive lean from rich (deterministic)
        run: |
          node scripts/derive-lean-from-rich.js
          if ! git diff --quiet -- methodologies/**/sections.json methodologies/**/rules.json; then
            echo "Lean JSON drift detected. Run: node scripts/derive-lean-from-rich.js";
            git --no-pager diff -- methodologies/**/sections.json methodologies/**/rules.json | sed -n '1,200p';
            exit 1;
          fi
      - name: Offline schema validation
        run: node scripts/validate-offline.js
      - name: Meta-driven source hash check
        run: node scripts/check-source-hash.js
      - name: Trio + registry integrity
        run: node scripts/check-trio-and-registry.js
