name: Schema Validate (META/sections/rules)
on: [push, pull_request]
jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i -g ajv-cli@5 jq
      - name: Validate META
        run: ajv validate -s schemas/META.schema.json -d 'methodologies/**/META.json'
      - name: Validate sections
        run: ajv validate -s schemas/sections.schema.json -d 'methodologies/**/sections.json'
      - name: Validate rules
        run: ajv validate -s schemas/rules.schema.json -d 'methodologies/**/rules.json'
